//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrunStokUygulama
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_musterı
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_musterı()
        {
            this.tbl_satıs = new HashSet<tbl_satıs>();
        }
    
        public int musterııd { get; set; }
        public string musterıad { get; set; }
        public string musterısoyad { get; set; }
        public string sehır { get; set; }
        public Nullable<bool> durum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_satıs> tbl_satıs { get; set; }
    }
}
