//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrunStokUygulama
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_satıs
    {
        public int satısıd { get; set; }
        public Nullable<int> urun { get; set; }
        public Nullable<int> musterı { get; set; }
        public Nullable<decimal> fıyat { get; set; }
        public Nullable<System.DateTime> tarıh { get; set; }
    
        public virtual tbl_musterı tbl_musterı { get; set; }
        public virtual tbl_urun tbl_urun { get; set; }
    }
}
